apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infrastructure-rag.fullname" . | default "infrastructure-rag" }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: infrastructure-rag
  template:
    metadata:
      labels:
        app: infrastructure-rag
    spec:
      containers:
        - name: infrastructure-rag
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
